<template>
  <div
    class="
      float-left
      relative
      hidden
      lg:flex
      flex-1
      self-stretch
      justify-items-center
    "
  >
    <div
      class="
        bg-white
        rounded-3xl
        absolute
        top-5
        xl:top-0
        left-0
        right-0
        xl:right-auto
        bottom-auto
        xl:bottom-0
        m-auto
        anim-website-main
        animate__animated animate__zoomIn
      "
    >
      <div class="anim-website-main w-full h-full p-2">
        <div class="w-full h-4 flex justify-end">
          <img
            class="h-full mx-2 pt-1"
            draggable="false"
            src="/animation/Windows-controll.svg"
          />
        </div>
        <div class="w-full flex">
          <div class="float-left w-12 h-12 m-2">
            <img
              class="
                w-full
                animate__animated
                animate__zoomIn
                animate__delay-5s
                animate__faster
              "
              src="/logo/WebStream-logo-min.svg"
              draggable="false"
            />
          </div>
          <div
            class="
              float-left
              w-full
              h-12
              m-2
              bg-webstream-gray
              rounded-lg
              animate__animated
              animate__zoomIn
              animate__delay-3s
              animate__faster
            "
          ></div>
        </div>
        <div class="w-full h-20 flex">
          <div
            class="
              float-left
              w-24
              h-full
              m-2
              bg-webstream-gray
              rounded-lg
              animate__animated
              animate__zoomIn
              animate__delay-3s
              animate__faster
            "
          ></div>
          <div class="flex w-full mx-2">
            <div class="w-full">
              <div
                class="
                  w-full
                  h-6
                  my-2
                  bg-webstream-gray
                  rounded-lg
                  animate__animated
                  animate__zoomIn
                  animate__delay-4s
                  animate__faster
                "
              ></div>
              <div
                class="
                  w-full
                  h-12
                  my-2
                  bg-webstream-gray
                  rounded-lg
                  animate__animated
                  animate__zoomIn
                  animate__delay-3s
                  animate__faster
                "
              ></div>
            </div>
          </div>
        </div>
        <div class="w-full h-28 flex my-4">
          <div class="mx-2 flex-1">
            <div class="flex w-full">
              <div class="w-full">
                <div
                  class="
                    w-full
                    h-6
                    my-2
                    bg-webstream-gray
                    rounded-lg
                    animate__animated
                    animate__zoomIn
                    animate__delay-4s
                    animate__faster
                  "
                ></div>
                <div
                  class="
                    w-full
                    h-20
                    my-2
                    bg-webstream-gray
                    rounded-lg
                    animate__animated
                    animate__zoomIn
                    animate__delay-3s
                    animate__faster
                  "
                ></div>
              </div>
            </div>
          </div>
          <div class="w-46 float-right">
            <div
              class="
                float-left
                w-24
                h-full
                m-2
                bg-webstream-gray
                rounded-lg
                animate__animated
                animate__zoomIn
                animate__delay-3s
                animate__faster
              "
            ></div>
            <div
              class="
                float-left
                w-24
                h-full
                m-2
                bg-webstream-gray
                rounded-lg
                animate__animated
                animate__zoomIn
                animate__delay-3s
                animate__faster
              "
            ></div>
          </div>
        </div>
      </div>
    </div>
    <div
      class="
        bg-webstream-darker
        rounded-3xl
        absolute
        top-auto
        xl:top-0
        bottom-5
        xl:bottom-0
        right-0
        xl:right-auto
        left-0
        m-auto
        anim-networking-main
        animate__animated animate__zoomIn
      "
    >
      <div class="w-full h-full">
        <div class="w-full p-2 h-8 px-4 flex border-b-2 border-white text-xs">
          <span class="flex-1"></span>
          <div class="flex flex-1 justify-center text-xs">Networking</div>
          <div class="flex flex-1 justify-end">
            <img
              class="flex h-full mx-2 pt-1"
              draggable="false"
              src="/animation/Windows-controll.svg"
            />
          </div>
        </div>
        <div
          class="
            w-full
            h-16
            flex
            border-b-2 border-white
            text-xs text-right
            relative
          "
        >
          <div class="float-left w-16 border-r-2 border-white text-xs px-1">
            50 ms
          </div>
          <div class="float-left w-16 border-r-2 border-white text-xs px-1">
            100 ms
          </div>
          <div class="float-left w-16 border-r-2 border-white text-xs px-1">
            150 ms
          </div>
          <div class="float-left w-16 border-r-2 border-white text-xs px-1">
            200 ms
          </div>
          <div class="float-left w-16 border-r-2 border-white text-xs px-1">
            250 ms
          </div>
          <div class="float-left w-16 border-r-2 border-white text-xs px-1">
            300 ms
          </div>
          <div class="float-left w-16 border-r-2 border-white text-xs px-1">
            350 ms
          </div>
          <div class="float-left w-16 border-r-2 border-white text-xs px-1">
            400 ms
          </div>
          <div
            class="
              bg-webstream-light
              w-28
              h-1
              top-4
              absolute
              animate__animated animate__zoomInLeft animate__delay-2s
            "
          ></div>
          <div
            class="
              bg-webstream-light
              left-32
              w-6
              h-1
              top-4
              absolute
              animate__animated animate__zoomInLeft animate__delay-2s
            "
          ></div>
          <div
            class="
              bg-webstream-light
              left-32
              w-6
              h-1
              top-6
              absolute
              animate__animated animate__zoomInLeft animate__delay-2s
            "
          ></div>
          <div
            class="
              bg-webstream-light
              left-32
              w-6
              h-1
              top-8
              absolute
              animate__animated animate__zoomInLeft animate__delay-2s
            "
          ></div>
          <div
            class="
              bg-webstream-light
              left-32
              w-8
              h-1
              top-10
              absolute
              animate__animated animate__zoomInLeft animate__delay-3s
            "
          ></div>
          <div
            class="
              bg-webstream-light
              left-32
              w-6
              h-1
              top-12
              absolute
              animate__animated animate__zoomInLeft animate__delay-2s
            "
          ></div>
          <div
            class="
              bg-webstream-light
              left-32
              w-10
              h-1
              top-14
              absolute
              animate__animated animate__zoomInLeft animate__delay-3s
            "
          ></div>
          <div
            class="
              bg-webstream-light
              left-44
              w-20
              h-1
              top-4
              absolute
              animate__animated animate__zoomInLeft animate__delay-4s
            "
          ></div>
        </div>
        <div class="border-white text-xs border-b-2">
          <div class="w-full flex border-b-2 border-white text-xs">
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-r-2 border-white
                text-xs
              "
            >
              Name
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-r-2 border-white
                text-xs
              "
            >
              Status
            </span>
            <span
              class="
                text-xs
                w-1/12
                h-full
                px-1
                py-0.5
                border-r-2 border-white
                text-xs
              "
            >
              Type
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-r-2 border-white
                text-xs
              "
            >
              Initiator
            </span>
            <span class="text-xs w-5/12 h-full px-1 py-0.5">Waterfall</span>
          </div>
          <div
            class="
              w-full
              flex
              even:bg-webstream-light even:bg-opacity-25
              text-xs
              animate__animated animate__zoomInRight animate__delay-1s
            "
          >
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              jloads.min.js
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              200
            </span>
            <span
              class="
                text-xs
                w-1/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              script
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              (index)
            </span>
            <span
              class="
                text-xs
                w-5/12
                h-full
                px-1
                py-0.5
                items-center
                text-center
                animate__animated animate__zoomInLeft animate__delay-2s
              "
            >
              <div
                class="bg-webstream-light w-10 h-3 my-auto my-0.5 ml-2"
              ></div>
            </span>
          </div>
          <div
            class="
              w-full
              flex
              even:bg-webstream-light even:bg-opacity-25
              text-xs
              animate__animated animate__zoomInRight animate__delay-2s
            "
          >
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              app.html
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              200
            </span>
            <span
              class="
                text-xs
                w-1/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              xhr
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              jloads.min.js
            </span>
            <span
              class="
                text-xs
                w-5/12
                h-full
                px-1
                py-0.5
                items-center
                text-center
                animate__animated animate__zoomInLeft animate__delay-2s
              "
            >
              <div class="bg-webstream-light w-2 h-3 my-auto my-0.5 ml-8"></div>
            </span>
          </div>
          <div
            class="
              w-full
              flex
              even:bg-webstream-light even:bg-opacity-25
              text-xs
              animate__animated animate__zoomInRight animate__delay-2s
            "
          >
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              header.html
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              200
            </span>
            <span
              class="
                text-xs
                w-1/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              xhr
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              jloads.min.js
            </span>
            <span
              class="
                text-xs
                w-5/12
                h-full
                px-1
                py-0.5
                items-center
                text-center
                animate__animated animate__zoomInLeft animate__delay-2s
              "
            >
              <div class="bg-webstream-light w-2 h-3 my-auto my-0.5 ml-8"></div>
            </span>
          </div>
          <div
            class="
              w-full
              flex
              even:bg-webstream-light even:bg-opacity-25
              text-xs
              animate__animated animate__zoomInRight animate__delay-2s
            "
          >
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              window.html
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              200
            </span>
            <span
              class="
                text-xs
                w-1/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              xhr
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              jloads.min.js
            </span>
            <span
              class="
                text-xs
                w-5/12
                h-full
                px-1
                py-0.5
                items-center
                text-center
                animate__animated animate__zoomInLeft animate__delay-2s
              "
            >
              <div class="bg-webstream-light w-2 h-3 my-auto my-0.5 ml-8"></div>
            </span>
          </div>
          <div
            class="
              w-full
              flex
              even:bg-webstream-light even:bg-opacity-25
              text-xs
              animate__animated animate__zoomInRight animate__delay-2s
            "
          >
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              title.html
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              200
            </span>
            <span
              class="
                text-xs
                w-1/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              xhr
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              jloads.min.js
            </span>
            <span
              class="
                text-xs
                w-5/12
                h-full
                px-1
                py-0.5
                items-center
                text-center
                animate__animated animate__zoomInLeft animate__delay-3s
              "
            >
              <div class="bg-webstream-light w-3 h-3 my-auto my-0.5 ml-8"></div>
            </span>
          </div>
          <div
            class="
              w-full
              flex
              even:bg-webstream-light even:bg-opacity-25
              text-xs
              animate__animated animate__zoomInRight animate__delay-2s
            "
          >
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              content.html
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              200
            </span>
            <span
              class="
                text-xs
                w-1/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              xhr
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              jloads.min.js
            </span>
            <span
              class="
                text-xs
                w-5/12
                h-full
                px-1
                py-0.5
                items-center
                text-center
                animate__animated animate__zoomInLeft animate__delay-2s
              "
            >
              <div class="bg-webstream-light w-2 h-3 my-auto my-0.5 ml-8"></div>
            </span>
          </div>
          <div
            class="
              w-full
              flex
              even:bg-webstream-light even:bg-opacity-25
              text-xs
              animate__animated animate__zoomInRight animate__delay-2s
            "
          >
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              logo-min.svg
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              200
            </span>
            <span
              class="
                text-xs
                w-1/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              svg
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              jloads.min.js
            </span>
            <span
              class="
                text-xs
                w-5/12
                h-full
                px-1
                py-0.5
                items-center
                text-center
                animate__animated animate__zoomInLeft animate__delay-4s
              "
            >
              <div class="bg-webstream-light w-4 h-3 my-auto my-0.5 ml-8"></div>
            </span>
          </div>
          <div
            class="
              w-full
              flex
              even:bg-webstream-light even:bg-opacity-25
              text-xs
              animate__animated animate__zoomInRight animate__delay-4s
            "
          >
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              favicon.ico
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              200
            </span>
            <span
              class="
                text-xs
                w-1/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              x-icon
            </span>
            <span
              class="
                text-xs
                w-2/12
                h-full
                px-1
                py-0.5
                border-white
                text-xs
                border-r-2
              "
            >
              Other
            </span>
            <span
              class="
                text-xs
                w-5/12
                h-full
                px-1
                py-0.5
                items-center
                text-center
                animate__animated animate__zoomInLeft animate__delay-5s
              "
            >
              <div
                class="bg-webstream-light w-8 h-3 my-auto my-0.5 ml-12"
              ></div>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<style scoped>
.anim-website-main {
  width: 480px;
  height: 320px;
}
.anim-networking-main {
  width: 520px;
  height: 360px;
}

@media (min-width: 1280px) {
  .anim-networking-main {
    width: 520px;
    height: 360px;
    left: 440px;
  }
}
</style>
